config/routes.rb
Rails.application.routes.draw do
  resources :variations
  resources :products
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :variations, dependent: :destroy
  accepts_nested_attributes_for :variations, allow_destroy: true
end

app/models/variation.rb
class Variation < ApplicationRecord
  belongs_to :product
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]

  # GET /products or /products.json
  def index
    @products = Product.all
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to product_url(@product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product), notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy!

    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :price, :photo)
    end
end

app/controllers/variations_controller.rb
class VariationsController < ApplicationController
  before_action :set_variation, only: %i[ show edit update destroy ]

  # GET /variations or /variations.json
  def index
    @variations = Variation.all
  end

  # GET /variations/1 or /variations/1.json
  def show
  end

  # GET /variations/new
  def new
    @variation = Variation.new
  end

  # GET /variations/1/edit
  def edit
  end

  # POST /variations or /variations.json
  def create
    @variation = Variation.new(variation_params)

    respond_to do |format|
      if @variation.save
        format.html { redirect_to variation_url(@variation), notice: "Variation was successfully created." }
        format.json { render :show, status: :created, location: @variation }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @variation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /variations/1 or /variations/1.json
  def update
    respond_to do |format|
      if @variation.update(variation_params)
        format.html { redirect_to variation_url(@variation), notice: "Variation was successfully updated." }
        format.json { render :show, status: :ok, location: @variation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @variation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /variations/1 or /variations/1.json
  def destroy
    @variation.destroy!

    respond_to do |format|
      format.html { redirect_to variations_url, notice: "Variation was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_variation
      @variation = Variation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def variation_params
      params.require(:variation).permit(:product_id, :size, :quantity)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/variations_helper.rb
module VariationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StockManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>

  <div>
    <%= form.label :photo, style: "display: block" %>
    <%= form.text_field :photo %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/products/_product.html.erb
<div id="<%= dom_id product %>">
  <p>
    <strong>Name:</strong>
    <%= product.name %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= product.price %>
  </p>

  <p>
    <strong>Photo:</strong>
    <%= product.photo %>
  </p>

</div>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Show this product", @product %> |
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Products</h1>

<div id="products">
  <% @products.each do |product| %>
    <%= render product %>
    <p>
      <%= link_to "Show this product", product %>
    </p>
  <% end %>
</div>

<%= link_to "New product", new_product_path %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @product %>

<div>
  <%= link_to "Edit this product", edit_product_path(@product) %> |
  <%= link_to "Back to products", products_path %>

  <%= button_to "Destroy this product", @product, method: :delete %>
</div>

app/views/variations/_form.html.erb
<%= form_with(model: variation) do |form| %>
  <% if variation.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(variation.errors.count, "error") %> prohibited this variation from being saved:</h2>

      <ul>
        <% variation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :product_id, style: "display: block" %>
    <%= form.text_field :product_id %>
  </div>

  <div>
    <%= form.label :size, style: "display: block" %>
    <%= form.text_field :size %>
  </div>

  <div>
    <%= form.label :quantity, style: "display: block" %>
    <%= form.number_field :quantity %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/variations/_variation.html.erb
<div id="<%= dom_id variation %>">
  <p>
    <strong>Product:</strong>
    <%= variation.product_id %>
  </p>

  <p>
    <strong>Size:</strong>
    <%= variation.size %>
  </p>

  <p>
    <strong>Quantity:</strong>
    <%= variation.quantity %>
  </p>

</div>

app/views/variations/edit.html.erb
<h1>Editing variation</h1>

<%= render "form", variation: @variation %>

<br>

<div>
  <%= link_to "Show this variation", @variation %> |
  <%= link_to "Back to variations", variations_path %>
</div>

app/views/variations/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Variations</h1>

<div id="variations">
  <% @variations.each do |variation| %>
    <%= render variation %>
    <p>
      <%= link_to "Show this variation", variation %>
    </p>
  <% end %>
</div>

<%= link_to "New variation", new_variation_path %>

app/views/variations/new.html.erb
<h1>New variation</h1>

<%= render "form", variation: @variation %>

<br>

<div>
  <%= link_to "Back to variations", variations_path %>
</div>

app/views/variations/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @variation %>

<div>
  <%= link_to "Edit this variation", edit_variation_path(@variation) %> |
  <%= link_to "Back to variations", variations_path %>

  <%= button_to "Destroy this variation", @variation, method: :delete %>
</div>